# MODEL = 'gpt-4o'
# MODEL = "deepseek/deepseek-r1-0528:free"
MODEL = "gemini-2.0-flash"

TEXT_MENTION_TERMINATION = 'STOP'
DOCKER_WORK_DIR = 'temp'
DOCKER_TIMEOUT=120
MAX_TURNS=15

# OPENAI_API_KEY = 'OPENAI_API_KEY'
OPENROUTER_API_KEY = 'OPENROUTER_API_KEY'
GEMINI_API_KEY = 'GEMINI_API_KEY'